# Generated by Django 4.2.7 on 2023-11-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
