# Generated by Django 4.2.7 on 2023-11-06 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0002_competitor_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
