# Generated by Django 4.2.7 on 2023-11-06 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_alter_lottery_first_name_alter_lottery_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottery',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='lottery',
            name='last_name',
        ),
        migrations.AddField(
            model_name='lottery',
            name='lottery_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
