# Generated by Django 4.2.7 on 2023-11-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0003_remove_lottery_first_name_remove_lottery_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottery',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lottery',
            name='phone_number',
        ),
    ]
