# Generated by Django 4.2.7 on 2023-11-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0004_remove_lottery_email_remove_lottery_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='winner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
